apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome
spec:
  replicas: 3
  selector:
    matchLabels:
      app: welcome
  template:
    metadata:
      labels:
        app: welcome
    spec:
      containers:
        - name: welcome
          image: your-container-registry.azurecr.io/your-image-name:latest
          ports:
            - containerPort: 8080
